name: Upsert Container
author: Luuk Brauckmann
description: Use this action to create or update a Container

inputs:
  api_key:
    description: The API key for your Bunny account
    required: true

  app_id:
    description: The Container Application ID.
    required: true

  container_name:
    description: The Container name.
    required: true

runs:
  using: 'node20'
  main: '.lib-action/index.js'

branding:
  color: 'orange'
  icon: 'delete'
