name: Get available port
author: Luuk Brauckmann
description: Use this action to get an unused port

inputs:
  api_key:
    description: The API key for your Bunny account
    required: true

  app_id:
    description: The Container Application ID.
    required: true

runs:
  using: node20
  main: .lib-action/index.js

branding:
  color: orange
  icon: search
